In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
df = pd.read_csv(r'C:\Datasets\NIFTY22JANFUT.csv')
df.head(5)

,Unnamed: 0,dateTime,open,high,low,close,volume
0,0,2021-12-23 09:15:00.0,17105.00,17129.95,17105.0,17106.15,0
1,1,2021-12-23 09:16:00.0,17106.05,17116.00,17100.3,17116.00,12050
2,2,2021-12-23 09:17:00.0,17116.15,17117.85,17102.7,17107.90,5800
3,3,2021-12-23 09:18:00.0,17107.90,17120.00,17107.9,17116.70,7450
4,4,2021-12-23 09:19:00.0,17116.70,17116.70,17105.4,17106.10,4600

In [6]:
del df['Unnamed: 0']

In [7]:
del df['dateTime']

In [8]:
df.head()

       open      high      low     close  volume
0  17105.00  17129.95  17105.0  17106.15       0
1  17106.05  17116.00  17100.3  17116.00   12050
2  17116.15  17117.85  17102.7  17107.90    5800
3  17107.90  17120.00  17107.9  17116.70    7450
4  17116.70  17116.70  17105.4  17106.10    4600

In [9]:
df['close_diff'] = df['close'].diff()

In [44]:
df.head()

       open      high      low     close  volume  close_diff  new_col
0  17105.00  17129.95  17105.0  17106.15       0         NaN        0
1  17106.05  17116.00  17100.3  17116.00   12050        9.85        1
2  17116.15  17117.85  17102.7  17107.90    5800       -8.10        0
3  17107.90  17120.00  17107.9  17116.70    7450        8.80        1
4  17116.70  17116.70  17105.4  17106.10    4600      -10.60        0

In [46]:
df["new_col"] = np.where(df["close_diff"]>0,1,0)

In [47]:
df.head()

       open      high      low     close  volume  close_diff  new_col
0  17105.00  17129.95  17105.0  17106.15       0         NaN        0
1  17106.05  17116.00  17100.3  17116.00   12050        9.85        1
2  17116.15  17117.85  17102.7  17107.90    5800       -8.10        0
3  17107.90  17120.00  17107.9  17116.70    7450        8.80        1
4  17116.70  17116.70  17105.4  17106.10    4600      -10.60        0

In [48]:
df.drop(df[df['close_diff'] == 0].index, inplace = True)

In [49]:
df

          open      high       low     close  volume  close_diff  new_col
0     17105.00  17129.95  17105.00  17106.15       0         NaN        0
1     17106.05  17116.00  17100.30  17116.00   12050        9.85        1
2     17116.15  17117.85  17102.70  17107.90    5800       -8.10        0
3     17107.90  17120.00  17107.90  17116.70    7450        8.80        1
4     17116.70  17116.70  17105.40  17106.10    4600      -10.60        0
...        ...       ...       ...       ...     ...         ...      ...
8296  17651.25  17653.55  17645.05  17647.65   44750       -6.35        0
8297  17647.95  17650.20  17645.00  17645.75   20550       -1.90        0
8298  17645.80  17650.00  17645.80  17650.00   34500        4.25        1
8299  17651.00  17651.00  17646.00  17647.75   43550       -2.25        0
8300  17647.35  17650.00  17644.00  17647.90   42150        0.15        1

[8130 rows x 7 columns]

In [50]:
X = df[['open' , 'high' ,'low' , 'close']]

In [51]:
X.head()

       open      high      low     close
0  17105.00  17129.95  17105.0  17106.15
1  17106.05  17116.00  17100.3  17116.00
2  17116.15  17117.85  17102.7  17107.90
3  17107.90  17120.00  17107.9  17116.70
4  17116.70  17116.70  17105.4  17106.10

In [52]:
y = df['new_col']

In [53]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: new_col, dtype: int32

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
clf_lrs = LogisticRegression()

In [56]:
clf_lrs.fit(X,y)

LogisticRegression()

In [57]:
clf_lrs.coef_

array([[-1.35335163,  0.01192179, -0.02131859,  1.36274275]])

In [58]:
clf_lrs.intercept_

array([-0.00069882])

In [59]:
clf_lrs.predict_proba(X)

array([[1.45968615e-01, 8.54031385e-01],
       [1.11968551e-06, 9.99998880e-01],
       [9.99983852e-01, 1.61477211e-05],
       ...,
       [3.42751145e-03, 9.96572489e-01],
       [9.88149386e-01, 1.18506141e-02],
       [3.20515002e-01, 6.79484998e-01]])

In [60]:
y_pred = clf_lrs.predict(X)
y_pred

array([1, 1, 0, ..., 1, 0, 1])

In [61]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y , y_pred)

array([[3841,  173],
       [ 295, 3821]], dtype=int64)

In [62]:
from sklearn.metrics import precision_score , recall_score

In [63]:
precision_score(y , y_pred)

0.956685027541312

In [64]:
recall_score(y, y_pred)

0.9283284742468416